
version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
