
version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
      - ./reservation.json:/mnt/locust/reservation.json
    command: -f /mnt/locust/locustfile.py
  
