version: '3.5'

services:
  kafka:
    image: docker.io/bitnami/kafka:3.6.0
    ports:
#      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_KRAFT_CLUSTER_ID: "OTA5Nzc2NTE1NDk3NGRiZD"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,EXTERNALPLAINTEXT://:29092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNALPLAINTEXT://localhost:29092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNALPLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNALPLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

#      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"

      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    restart: unless-stopped

  debezium:
    image: debezium/connect:2.4
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my-connect-configs"
      OFFSET_STORAGE_TOPIC: "my-connect-offsets"
      BOOTSTRAP_SERVERS: "kafka:9092"
#    ports:
#      - "8083:8083"
    depends_on:
      - kafka
    restart: unless-stopped

  debezium-config:
    build: .
    command: "/app/init-script.sh"
    environment:
      CONNECTOR_NAME: "housekeeping-service-connector"
      CONNECTOR_CLASS: "io.debezium.connector.postgresql.PostgresConnector"
      DB_HOSTNAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "P4ssword!"
      DB_NAME: "house-keeping"
      DB_SERVER_ID: "1001"
      TOPIC_PREFIX: "postgres-dbserver1"
      PLUGIN_NAME: "pgoutput"
    depends_on:
      - debezium

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "SUPER_SECRET_PASSWORD"]
    restart: unless-stopped
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "house-keeping"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P4ssword!"
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=1", "-c", "max_replication_slots=1"]
    restart: unless-stopped

